# General Jekyll Config
auto: true
exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]

# Member list
#
# Required fields: `name`
# Optional fields: `twitter`, `url`
members:
  - name: Kyle Shipley
    twitter: kyleashipley

  - name: Anthony Panozzo
    twitter: panozzaj

  - name: Matt Swanson
    twitter: _swanson

  - name: Monica Mazda
    url: http://www.linkedin.com/pub/monica-mazda/31/b89/a93

  - name: Tony Dewan
    twitter: tonydewan

  - name: Alex Toumey
    twitter: atoumey

  - name: Alex Lopes
    twitter: IamAlexLopes

  - name: Eliza Brock
    twitter: elizabrock

  - name: Wes Winham
    twitter: weswinham

  - name: Anthony Smith
    twitter: sticksnleaves

  - name: Dave Mathew
    twitter: mathewda

  - name: Courtny Cotten
    twitter: courtnycotten

  - name: Trey Buck
    twitter: treybuck

  - name: Winston Kotzan
    twitter: winstonkotzan

  - name: Hank Graves
    twitter: hankgraves

  - name: Todd Grotenhuis
    twitter: toddgrotenhuis

  - name: Jacob Krall
    twitter: InPermutation

  - name: Jennifer Krall
    twitter: jennifertwk

  - name: Kail Keusch
    twitter: kfkkail

  - name: Michael Fellows
    twitter: 2Chili4U
    
  - name: Joel Dart
    twitter: joeldart

# Projects list
#
# Required fields: `name`, `img`, `desc`, `url`, `members`
projects:
  - name: RailsThemes
    img: railsthemes.png
    desc: |
      Beautiful themes for your Rails app, sliced into HTML and CSS and customized 
      for your gems and tools.
    url: https://railsthemes.com
    members: Anthony and Eliza

  - name: Morale
    img: moraleapp.png
    desc: |
      Daily team mood tracking.
    url: https://www.moraleapp.com/
    members: Matt

  - name: AwesomeController
    img: awesomecontroller.png
    desc: | 
      Awesome Controller lets you play retro video game systems with modern wireless 
      controllers.
    url: http://www.awesomecontroller.com/
    members: Team WAKKA

  - name: paperplane
    img: paperplane.png
    desc: |
      Radically simple static hosting. Dropbox in. Website out.
    url: http://www.paperplane.io/
    members: Kyle and Tony

  - name: ClassRealm
    img: classrealm.png
    desc: |
      ClassRealm provides a platform for teachers to introduce gamification into their 
      classrooms, encourage better behavior patterns, and promote creative expression.
    url: http://www.classrealm.com
    members: Dave and Courtny

  - name: Generic Space Shooter
    img: genericspaceshooter.png
    desc: |
      A generic space shooter game using CoffeeScript and HTML5 canvas, like Galaga 
      but store brand.
    url: https://github.com/shipstar/space-shooter
    members: Kyle and Anthony

  - name: 5 Day Prototype
    img: fivedayprototype.png
    desc: |
      Get the ideas out of your head and into the world. Five day rapid prototyping for 
      your startup or product.
    url: http://www.fivedayprototype.com/
    members: Kyle and Tony

  - name: Equity Steaks
    img: equitysteaks.jpg
    desc: |
      An employee compensation plan that's well done.
    url: http://www.equitysteaks.com
    members: Kyle, Tony, Matt, and Michael


